/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.DAO_Jenis_Barang;
import dao.Pengguna_DAO;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JOptionPane;
import model.Model_Jenis_Barang;
import service.Service_Pengguna;
import tabelmodel.TableMod_Pengguna;


/**
 *
 * @author UsEr
 */
public class form_pengguna extends javax.swing.JPanel {
     private Service_Pengguna servis = new Pengguna_DAO();
    private TableMod_Pengguna tblModel = new TableMod_Pengguna();
    
       

    public form_pengguna() {
        initComponents();
         setPreferredWidth();
         this.tbl_barang.setModel(tblModel);
        loadData();
        btn_tambah.setBackground(new Color(0,167,98));
        btn_hapus.setBackground(new Color(0,167,98));
        btn_batal.setBackground(new Color(0,167,98));
        btn_tambah1.setBackground(new Color(0,167,98));
        btn_batal1.setBackground(new Color(0,167,98));
        
        tbl_barang.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        tbl_barang.getTableHeader().setForeground(Color.WHITE);
        tbl_barang.getTableHeader().setOpaque(false);
        tbl_barang.getTableHeader().setBackground(new Color(0,167,98));
        tbl_barang.setRowHeight(28);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        TampilanData = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_tambah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_barang = new javax.swing.JTable();
        TambahData = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_tambah1 = new javax.swing.JButton();
        txt_kodejenisbarang = new javax.swing.JTextField();
        btn_batal1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_namajenisbarang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbxKd = new javax.swing.JComboBox<>();
        TxtPilih = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        TampilanData.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 167, 98));
        jLabel2.setText("Pengguna");

        btn_tambah.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btn_tambah.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tambah.png"))); // NOI18N
        btn_tambah.setText(" Tambah");
        btn_tambah.setBorder(null);
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_hapus.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hapus.png"))); // NOI18N
        btn_hapus.setText(" Hapus");
        btn_hapus.setBorder(null);
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_batal.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btn_batal.setForeground(new java.awt.Color(255, 255, 255));
        btn_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-cancel-30.png"))); // NOI18N
        btn_batal.setText("Batal");
        btn_batal.setBorder(null);
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        tbl_barang.setBackground(new java.awt.Color(255, 255, 255));
        tbl_barang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Kode Jenis Barang", "Nama Jenis Barang"
            }
        ));
        tbl_barang.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbl_barang.setRowHeight(35);
        tbl_barang.getTableHeader().setReorderingAllowed(false);
        tbl_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_barangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_barang);

        javax.swing.GroupLayout TampilanDataLayout = new javax.swing.GroupLayout(TampilanData);
        TampilanData.setLayout(TampilanDataLayout);
        TampilanDataLayout.setHorizontalGroup(
            TampilanDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TampilanDataLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(TampilanDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(TampilanDataLayout.createSequentialGroup()
                        .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        TampilanDataLayout.setVerticalGroup(
            TampilanDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TampilanDataLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(TampilanDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2)
                .addGap(30, 30, 30))
        );

        mainPanel.add(TampilanData, "card2");

        TambahData.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 167, 98));
        jLabel3.setText("Tambah Jenis Barang");

        btn_tambah1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btn_tambah1.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tambah.png"))); // NOI18N
        btn_tambah1.setText(" Tambah");
        btn_tambah1.setBorder(null);
        btn_tambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah1ActionPerformed(evt);
            }
        });

        txt_kodejenisbarang.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        txt_kodejenisbarang.setForeground(new java.awt.Color(0, 0, 0));
        txt_kodejenisbarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_kodejenisbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kodejenisbarangActionPerformed(evt);
            }
        });

        btn_batal1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btn_batal1.setForeground(new java.awt.Color(255, 255, 255));
        btn_batal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-cancel-30.png"))); // NOI18N
        btn_batal1.setText("Batal");
        btn_batal1.setBorder(null);
        btn_batal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nama Kode");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nama Jenis Barang");

        txt_namajenisbarang.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        txt_namajenisbarang.setForeground(new java.awt.Color(0, 0, 0));
        txt_namajenisbarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_namajenisbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namajenisbarangActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Kode Jenis Barang");

        cbxKd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RKR", "MYK", "KP", "SBN", "MI" }));
        cbxKd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxKdActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TambahDataLayout = new javax.swing.GroupLayout(TambahData);
        TambahData.setLayout(TambahDataLayout);
        TambahDataLayout.setHorizontalGroup(
            TambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TambahDataLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(TambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addGroup(TambahDataLayout.createSequentialGroup()
                        .addComponent(btn_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btn_batal1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(TambahDataLayout.createSequentialGroup()
                        .addComponent(cbxKd, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(TxtPilih, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButton1))
                    .addGroup(TambahDataLayout.createSequentialGroup()
                        .addComponent(txt_namajenisbarang, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                        .addGap(8, 8, 8))
                    .addComponent(txt_kodejenisbarang))
                .addGap(30, 30, 30))
        );
        TambahDataLayout.setVerticalGroup(
            TambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TambahDataLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addGroup(TambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(TambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(TxtPilih)
                    .addComponent(cbxKd))
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGap(15, 15, 15)
                .addComponent(txt_kodejenisbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGap(15, 15, 15)
                .addComponent(txt_namajenisbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        mainPanel.add(TambahData, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
      mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(TambahData);
        mainPanel.repaint();
        mainPanel.revalidate();  
        btn_tambah1.setText("SIMPAN");
        DAO_Jenis_Barang dao = new DAO_Jenis_Barang();
    String nomorUrutan = dao.nomor(); 
    
    // Mendapatkan nilai dari JComboBox
    String kodeJenis = (String) cbxKd.getSelectedItem(); 
    
    // Menggabungkan nilai JComboBox dengan nomor urutan
    String kodeGabungan = kodeJenis + nomorUrutan; 
    
    // Mengatur nilai gabungan ke txt_kodejenisbarang
    txt_kodejenisbarang.setText(kodeGabungan);
    txt_kodejenisbarang.setEnabled(false);
        
        if(btn_tambah.getText().equals("UBAH")){
            dataTabel(); 
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        hapusData();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        tampilPanel();
        loadData();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_tambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah1ActionPerformed
        if(btn_tambah1.getText().equals("TAMBAH"))
        {
            btn_tambah1.setText("SIMPAN");
            txt_kodejenisbarang.setText(servis.nomor());
            
        }else if (btn_tambah1.getText().equals("SIMPAN"))
        
        {
            simpanData();
            
        }
        else if (btn_tambah1.getText().equals("PERBARUI"))
        {
            perbaruiData(); 
        }
    }//GEN-LAST:event_btn_tambah1ActionPerformed

    private void btn_batal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal1ActionPerformed
        tampilPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_btn_batal1ActionPerformed

    private void txt_namajenisbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namajenisbarangActionPerformed
        simpanData();
    }//GEN-LAST:event_txt_namajenisbarangActionPerformed

    private void tbl_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_barangMouseClicked
        if(btn_tambah.getText().equals("TAMBAH")){
           
        }
        btn_tambah.setText("UBAH");
        btn_hapus.setVisible(true);
        btn_batal.setVisible(true);
    }//GEN-LAST:event_tbl_barangMouseClicked

    private void txt_kodejenisbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kodejenisbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kodejenisbarangActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String adr = TxtPilih.getText();
        
        cbxKd.addItem(adr);
        
        TxtPilih.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbxKdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxKdActionPerformed
        DAO_Jenis_Barang dao = new DAO_Jenis_Barang();
    String nomorUrutan = dao.nomor(); 
    
    // Mendapatkan nilai dari JComboBox
    String kodeJenis = (String) cbxKd.getSelectedItem(); 
    
    // Menggabungkan nilai JComboBox dengan nomor urutan
    String kodeGabungan = kodeJenis + nomorUrutan; 
    
    // Mengatur nilai gabungan ke txt_kodejenisbarang
    txt_kodejenisbarang.setText(kodeGabungan);
    }//GEN-LAST:event_cbxKdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TambahData;
    private javax.swing.JPanel TampilanData;
    private javax.swing.JTextField TxtPilih;
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_batal1;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_tambah1;
    private javax.swing.JComboBox<String> cbxKd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable tbl_barang;
    private javax.swing.JTextField txt_kodejenisbarang;
    private javax.swing.JTextField txt_namajenisbarang;
    // End of variables declaration//GEN-END:variables

    private void dataTabel() {
        TambahData.setVisible(false);
        TambahData.setVisible(true);
        
        int row = tbl_barang.getSelectedRow();
        jLabel2.setText("Perbarui Data Jenis Barang");
        
        txt_kodejenisbarang.setEnabled(false);
        txt_namajenisbarang.setEnabled(true);
        
        
        txt_kodejenisbarang.setText(tbl_barang.getModel().getValueAt(row, 1).toString());
        txt_namajenisbarang.setText(tbl_barang.getModel().getValueAt(row, 2).toString());
     
        btn_tambah1.setText("PERBARUI");
        btn_batal.setVisible(true);
    }

    private void hapusData() {
        int index = tbl_barang.getSelectedRow();
        if(index !=-1){
            Model_Jenis_Barang jbr = tblModel.getData(tbl_barang.convertRowIndexToModel(index));
            if(JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus?", "Konfirmasi",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
                servis.hapusData(jbr);
                tblModel.hapusData(index);
                loadData();
                resetForm();
            }   
        }else{
            JOptionPane.showMessageDialog(null, "Pilih dulu record yang akan diupdate");
        }
    }

    private void tampilPanel() {
         mainPanel.removeAll();
       mainPanel.add(new form_pengguna());
       mainPanel.repaint();
       mainPanel.revalidate();
    }

    private void loadData() {
       btn_hapus.setVisible(false);
        btn_batal.setVisible(false);
        List<Model_Jenis_Barang> list = servis.getData();
        tblModel.setData(list);
        setPreferredWidth();  // Memastikan bahwa metode setPreferredWidth dipanggil setelah memuat data
        tbl_barang.revalidate();  // Menjalankan pembaruan UI
        tbl_barang.repaint();  // Menjalankan pembaruan UI
    }

    private void simpanData() {
         String kode = txt_kodejenisbarang.getText();
        String nama = txt_namajenisbarang.getText();
        
        Model_Jenis_Barang jb = new Model_Jenis_Barang();
        jb.setId_kategori(kode);
        jb.setNama_kategori(nama);
        
        if(servis.validasiNamaJenisBarang(jb)==true)
        {
            if (validasiInput()==true) {
                
                String kode_jenis = txt_kodejenisbarang.getText();
                String nama_jenis = txt_namajenisbarang.getText();
                
                Model_Jenis_Barang jbr = new Model_Jenis_Barang();
       
                jbr.setId_kategori(kode_jenis);
                jbr.setNama_kategori(nama_jenis);     

                servis.tambahData(jb);
                tblModel.tambahData(jb);
                
                tampilPanel();
                loadData();
                resetForm();
                btn_tambah.setText("TAMBAH");
            }
        
            }else{
            txt_namajenisbarang.requestFocus();
        }    
    }

    private void perbaruiData() {
        int index = tbl_barang.getSelectedRow();
        if(index!=-1){
            Model_Jenis_Barang mobar = tblModel.getData(tbl_barang.convertRowIndexToModel(index));
            
            if(servis.validasiNamaJenisBarang(mobar)==true)
            {   
                    if(validasiInput()== true){

                        String kode_jenis = txt_kodejenisbarang.getText();
                        String nama_jenis = txt_namajenisbarang.getText();

                        Model_Jenis_Barang jbr = new Model_Jenis_Barang();

                        jbr.setId_kategori(kode_jenis);               
                        jbr.setNama_kategori(nama_jenis);

                        servis.perbaruiData(jbr);
                        tblModel.perbaruiData(index,jbr);

                        loadData();
                        resetForm();
                        tampilPanel();          
                } }else{
            txt_namajenisbarang.requestFocus();
        }    
                
            }
    }

    private void resetForm() {
        btn_tambah.requestFocus();
        btn_tambah.setText("TAMBAH");
        txt_kodejenisbarang.setText("");
        txt_namajenisbarang.setText("");
    }

    private boolean setPreferredWidth() {
        if (tbl_barang.getColumnCount() > 0) {
            tbl_barang.getColumnModel().getColumn(0).setPreferredWidth(20);
            tbl_barang.getColumnModel().getColumn(1).setPreferredWidth(269);
            tbl_barang.getColumnModel().getColumn(2).setPreferredWidth(269);
        }
         return false;
    }
  

    private boolean validasiInput() {
        boolean valid = false;
    if (txt_kodejenisbarang.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Kode jenis Barang Tidak Boleh Kosong");
    } else if (txt_namajenisbarang.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Nama Jenis Barang Tidak Boleh Kosong");
    } else {
        valid = true;
    }
    return valid;
        
        
    }
    
    
}
