/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.DAO_Det_Penjualan;
import dao.DAO_Penjualan;
import dao.DAO_semPenjualan;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JOptionPane;
import model.Model_Jenis_Barang;
import model.Model_Penjualan;
import model.Model_Detai_penjualan;
import model.Model_Barang;
import model.Model_SemPenjualan;
import service.Service_Penjualan;
import service.Service_Detail_Penjualan;
import service.Service_Sem_Penjualan;
import tabelmodel.Tablemod_Penjualan;
import tabelmodel.Tablemod_SemPenjualan;
import tabelmodel.Tablemod_DetPenjualan;




/**
 *
 * @author UsEr
 */
public class Menu_Barangmasuk extends javax.swing.JPanel {
    private Service_Penjualan service_penjualan = new DAO_Penjualan();
    private Service_Detail_Penjualan service_det = new DAO_Det_Penjualan();
    private Service_Sem_Penjualan service_sem = new DAO_semPenjualan();
    
    private Tablemod_Penjualan tblModel_penjualan = new Tablemod_Penjualan();
    private Tablemod_DetPenjualan tblModel_det = new Tablemod_DetPenjualan();
    private Tablemod_SemPenjualan tblModel_sem = new Tablemod_SemPenjualan();
    
    private String selectNO;
   
  

    public Menu_Barangmasuk() {
        initComponents();
        tbl_barang.setModel(tblModel_penjualan);
        tbl_detail.setModel(tblModel_det);
        tbl_sementara.setModel(tblModel_sem);
        loadData();
        loadDataSementara();
        
        setPreferredWidth();
        tbl_detail.setVisible(true);
        
        btn_tambah.setBackground(new Color(60,211,173));
        btn_hapus.setBackground(new Color(60,211,173));
        btn_batal.setBackground(new Color(60,211,173));
        btn_tambah1.setBackground(new Color(60,211,173));
        btn_batal1.setBackground(new Color(60,211,173));
        btn_pilih.setBackground(new Color(60,211,173));
        btn_hapusem.setBackground(new Color(60,211,173));
        btn_hapusem.setBackground(new Color(60,211,173));
        btn_tambahsementara.setBackground(new Color(60,211,173));
        btn_perbarisem.setBackground(new Color(60,211,173));
        
        tbl_barang.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        tbl_barang.getTableHeader().setForeground(Color.WHITE);
        tbl_barang.getTableHeader().setOpaque(false);
        tbl_barang.getTableHeader().setBackground(new Color(60,211,173));
        tbl_barang.setRowHeight(28);
        
        tbl_detail.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        tbl_detail.getTableHeader().setForeground(Color.WHITE);
        tbl_detail.getTableHeader().setOpaque(false);
        tbl_detail.getTableHeader().setBackground(new Color(60,211,173));
        tbl_detail.setRowHeight(28);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        TampilanData = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_tambah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_barang = new javax.swing.JTable();
        pn_detail = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_detail = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TambahData = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_no = new javax.swing.JTextField();
        txt_tanggal = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_kodebarang = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btn_pilih = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        lb_satan = new javax.swing.JLabel();
        txt_satuan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_harga = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_jumlah = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_subtotal = new javax.swing.JTextField();
        lb_stok = new javax.swing.JLabel();
        txt_stok = new javax.swing.JTextField();
        txt_namabarang = new javax.swing.JTextField();
        btn_tambahsementara = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_sementara = new javax.swing.JTable();
        btn_perbarisem = new javax.swing.JButton();
        btn_hapusem = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lb_total = new javax.swing.JLabel();
        btn_tambah1 = new javax.swing.JButton();
        btn_batal1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        TampilanData.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 167, 98));
        jLabel2.setText("Data Penjualan");

        btn_tambah.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btn_tambah.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tambah.png"))); // NOI18N
        btn_tambah.setText(" Tambah");
        btn_tambah.setBorder(null);
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_hapus.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hapus.png"))); // NOI18N
        btn_hapus.setText(" Hapus");
        btn_hapus.setBorder(null);
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_batal.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btn_batal.setForeground(new java.awt.Color(255, 255, 255));
        btn_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-cancel-30.png"))); // NOI18N
        btn_batal.setText("Batal");
        btn_batal.setBorder(null);
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        tbl_barang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Kode Jenis Barang", "Nama Jenis Barang"
            }
        ));
        tbl_barang.setRowHeight(35);
        tbl_barang.getTableHeader().setReorderingAllowed(false);
        tbl_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_barangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_barang);

        tbl_detail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_detail.setRowHeight(30);
        tbl_detail.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbl_detailAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbl_detail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_detailMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbl_detail);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Detail Pembelian Barang");

        jLabel7.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel7.setText("X");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pn_detailLayout = new javax.swing.GroupLayout(pn_detail);
        pn_detail.setLayout(pn_detailLayout);
        pn_detailLayout.setHorizontalGroup(
            pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_detailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(21, 21, 21))
            .addComponent(jScrollPane5)
        );
        pn_detailLayout.setVerticalGroup(
            pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_detailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TampilanDataLayout = new javax.swing.GroupLayout(TampilanData);
        TampilanData.setLayout(TampilanDataLayout);
        TampilanDataLayout.setHorizontalGroup(
            TampilanDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TampilanDataLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(TampilanDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TampilanDataLayout.createSequentialGroup()
                        .addGroup(TampilanDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(TampilanDataLayout.createSequentialGroup()
                                .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(TampilanDataLayout.createSequentialGroup()
                        .addGroup(TampilanDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                            .addComponent(pn_detail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30))))
        );
        TampilanDataLayout.setVerticalGroup(
            TampilanDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TampilanDataLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(TampilanDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addGap(50, 50, 50)
                .addComponent(pn_detail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        mainPanel.add(TampilanData, "card2");

        TambahData.setBackground(new java.awt.Color(255, 255, 255));
        TambahData.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Tambah Barang Pembelian");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(60, 211, 173));

        jLabel9.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("No Penjualan");

        jLabel4.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tanggal");

        txt_tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tanggalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_no, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_no, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 211, 173)));

        jPanel4.setBackground(new java.awt.Color(60, 211, 173));

        jLabel10.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Barang");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txt_kodebarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 211, 173)));

        jLabel11.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(60, 211, 173));
        jLabel11.setText("Kode Barang");

        btn_pilih.setText("jButton1");
        btn_pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pilihActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(60, 211, 173));
        jLabel12.setText("Nama Barang");

        lb_satan.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        lb_satan.setForeground(new java.awt.Color(60, 211, 173));
        lb_satan.setText("Satuan");

        txt_satuan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 211, 173)));

        jLabel13.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(60, 211, 173));
        jLabel13.setText("Harga");

        txt_harga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 211, 173)));

        jLabel14.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(60, 211, 173));
        jLabel14.setText("Jumlah");

        txt_jumlah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 211, 173)));
        txt_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlahActionPerformed(evt);
            }
        });
        txt_jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_jumlahKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(60, 211, 173));
        jLabel15.setText("Subtotal");

        txt_subtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 211, 173)));

        lb_stok.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        lb_stok.setForeground(new java.awt.Color(60, 211, 173));
        lb_stok.setText("Stok");

        txt_stok.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 211, 173)));

        txt_namabarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 211, 173)));

        btn_tambahsementara.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambahsementara.setText("TAMBAH BARANG");
        btn_tambahsementara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahsementaraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_kodebarang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_pilih, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_namabarang)
                    .addComponent(txt_satuan)
                    .addComponent(txt_harga)
                    .addComponent(txt_stok)
                    .addComponent(txt_jumlah)
                    .addComponent(txt_subtotal)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(lb_satan)
                            .addComponent(jLabel13)
                            .addComponent(lb_stok)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(btn_tambahsementara)
                .addGap(138, 138, 138))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pilih, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_namabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_satan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_stok)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_tambahsementara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbl_sementara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_sementara.setRowHeight(30);
        tbl_sementara.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbl_sementaraAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbl_sementara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_sementaraMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_sementara);

        btn_perbarisem.setForeground(new java.awt.Color(255, 255, 255));
        btn_perbarisem.setText("PERBARUI");
        btn_perbarisem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_perbarisemActionPerformed(evt);
            }
        });

        btn_hapusem.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapusem.setText("HAPUS");
        btn_hapusem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_perbarisem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btn_hapusem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_perbarisem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_hapusem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        lb_total.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_total.setText("Total Pesan");
        lb_total.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lb_totalAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(lb_total)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addComponent(lb_total))
        );

        btn_tambah1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btn_tambah1.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tambah.png"))); // NOI18N
        btn_tambah1.setText("SIMPAN");
        btn_tambah1.setBorder(null);
        btn_tambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah1ActionPerformed(evt);
            }
        });

        btn_batal1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btn_batal1.setForeground(new java.awt.Color(255, 255, 255));
        btn_batal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-cancel-30.png"))); // NOI18N
        btn_batal1.setText("Batal");
        btn_batal1.setBorder(null);
        btn_batal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Total Pesan");

        javax.swing.GroupLayout TambahDataLayout = new javax.swing.GroupLayout(TambahData);
        TambahData.setLayout(TambahDataLayout);
        TambahDataLayout.setHorizontalGroup(
            TambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TambahDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(TambahDataLayout.createSequentialGroup()
                        .addComponent(btn_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btn_batal1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(TambahDataLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        TambahDataLayout.setVerticalGroup(
            TambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TambahDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TambahDataLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TambahDataLayout.createSequentialGroup()
                        .addGroup(TambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_batal1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(TambahData, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(TambahData);
        mainPanel.repaint();
        mainPanel.revalidate();  
        
        btn_tambah1.setText("SIMPAN");
        txt_no.setEnabled(false);
        txt_tanggal.setEnabled(false);
        
        txt_no.setText(service_penjualan.nomor());
        
        Model_Detai_penjualan det_penjualan =new Model_Detai_penjualan();
        service_det.sumTotal(det_penjualan);
        lb_total.setText(det_penjualan.getSub_total().toString());
        setTanggal();
        
 
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        hapusData();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        tampilPanel();
        loadData();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void tbl_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_barangMouseClicked
        int row = tbl_barang.getSelectedRow();
        String id = tbl_barang.getValueAt(row, 0).toString();
        btn_tambah.setText("UBAH");
        btn_hapus.setVisible(true);
        btn_batal.setVisible(true);
        
        pn_detail.setVisible(true);
        List<Model_Detai_penjualan> list = service_det.getData(id);
        tblModel_det.setData(list);
         
    }//GEN-LAST:event_tbl_barangMouseClicked

    private void txt_tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tanggalActionPerformed

    private void btn_pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pilihActionPerformed
        boolean closable = true;
        Data_Produk mod_bar = new Data_Produk(null, closable);
        mod_bar.setVisible(true);
        
        txt_kodebarang.setText  (mod_bar.brg.getId_produk());
        txt_namabarang.setText  (mod_bar.brg.getNama_produk());
        txt_satuan.setText      (mod_bar.brg.getSatuan());
        txt_harga.setText(mod_bar.brg.getHarga());
        txt_stok.setText        (mod_bar.brg.getStok().toString());

        
        txt_kodebarang.setEnabled(false);
        txt_namabarang.setEnabled(false);
        txt_satuan.setEnabled(false);
        txt_harga.setEnabled(false);
        txt_stok.setEnabled(false);
        
        txt_jumlah.requestFocus();

    }//GEN-LAST:event_btn_pilihActionPerformed

    private void txt_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlahActionPerformed

    }//GEN-LAST:event_txt_jumlahActionPerformed

    private void txt_jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jumlahKeyReleased
        Integer harga, jumlah, subtotal;
        harga = Integer.parseInt(txt_harga.getText());
        String inputJumlah = txt_jumlah.getText();
        if(inputJumlah.isEmpty()){
            jumlah = 0;
        }else {
            jumlah = Integer.parseInt(inputJumlah);
        }
        subtotal = harga * jumlah;
        txt_subtotal.setText(Integer.toString(subtotal));
        btn_tambahsementara.requestFocus();
    }//GEN-LAST:event_txt_jumlahKeyReleased

    private void tbl_sementaraAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbl_sementaraAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_sementaraAncestorAdded

    private void tbl_sementaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_sementaraMouseClicked
        int row = tbl_sementara.getSelectedRow();

        txt_kodebarang.setEnabled(false);
        txt_namabarang.setEnabled(false);
        txt_satuan.setEnabled(false);
        txt_harga.setEnabled(false);
        txt_stok.setEnabled(false);
        txt_subtotal.setEnabled(false);

        txt_kodebarang.setText(tbl_sementara.getModel().getValueAt(row, 0).toString());
        txt_namabarang.setText(tbl_sementara.getModel().getValueAt(row, 1).toString());
        txt_harga.setText(tbl_sementara.getModel().getValueAt(row, 2).toString());
        txt_stok.setText(tbl_sementara.getModel().getValueAt(row, 3).toString());
        txt_jumlah.setText(tbl_sementara.getModel().getValueAt(row, 4).toString());
        txt_subtotal.setText(tbl_sementara.getModel().getValueAt(row, 5).toString());

        txt_jumlah.setVisible(true);
        lb_satan.setVisible(false);
        txt_satuan.setVisible(false);
//        lb_stok.setVisible(false);
//        txt_stok.setVisible(false);
        btn_tambahsementara.setVisible(false);
        btn_hapusem.setVisible(true);

    }//GEN-LAST:event_tbl_sementaraMouseClicked

    private void lb_totalAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lb_totalAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_totalAncestorAdded

    private void btn_tambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah1ActionPerformed
        if(btn_tambah1.getText().equals("TAMBAH")){
            btn_tambah1.setText("SIMPAN");
            
        }else if (btn_tambah1.getText().equals("SIMPAN")){
            simpanData();
            String no = txt_no.getText();
        }
            
    }//GEN-LAST:event_btn_tambah1ActionPerformed

    private void btn_batal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal1ActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(TampilanData);
    }//GEN-LAST:event_btn_batal1ActionPerformed

    private void btn_hapusemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusemActionPerformed
         int index = tbl_sementara.getSelectedRow();
        if(index != -1){
            Model_SemPenjualan model = tblModel_sem.getData(tbl_sementara.convertColumnIndexToModel(index));
            if(JOptionPane.showConfirmDialog(null, "Yakin Data Akan di Hapus", 
                    "Konfirmasi", JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
                service_sem.hapusData(model);
                tblModel_sem.hapusData(index);
                loadDataSementara();
                resetForm();
                bersihBarang();
                lb_satan.setVisible(true);
                txt_satuan.setVisible(true);
                btn_tambahsementara.setVisible(true);   
            }
        }else{
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan di update");
        }
        loadDataSementara();
        resetForm();
        bersihBarang();
        lb_satan.setVisible(true);
        txt_satuan.setVisible(true);
        btn_tambahsementara.setVisible(true);
    }//GEN-LAST:event_btn_hapusemActionPerformed

    private void tbl_detailAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbl_detailAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_detailAncestorAdded

    private void tbl_detailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_detailMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_detailMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        pn_detail.setVisible(false);
        tampilPanel();
        loadData();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void btn_tambahsementaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahsementaraActionPerformed
        String kode = txt_kodebarang.getText();
        String nama = txt_namabarang.getText();
        
        Long harga = Long.parseLong(txt_harga.getText());
        int jumlah = Integer.parseInt(txt_jumlah.getText());
        Long subtotal  = Long.parseLong(txt_subtotal.getText());
        
        Model_Barang brg = new Model_Barang();
        Model_Detai_penjualan detJual = new Model_Detai_penjualan();
        Model_Penjualan jual = new Model_Penjualan();
        Model_SemPenjualan semjual = new Model_SemPenjualan();
        
        brg.setId_produk(kode);
        brg.setNama_produk(nama);
        brg.setHarga(harga);
        
        detJual.setJumlah(jumlah);
        detJual.setSub_total(subtotal);
        
        semjual.setMod_bararang(brg);
        semjual.setMod_detpenjualan(detJual);
        
        service_sem.tambahData(semjual);
        service_det.sumTotal(detJual);
        lb_total.setText(detJual.getSub_total().toString());
        
        loadDataSementara();
        
        if(JOptionPane.showConfirmDialog(this, "Mau Tambah Barang?",
                "Konfirmasi", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            aktifBarang();
            bersihBarang();
            btn_pilih.requestFocus();
                       
        }else {
            aktifBarang();
            bersihBarang();
        }

    }//GEN-LAST:event_btn_tambahsementaraActionPerformed

    private void btn_perbarisemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_perbarisemActionPerformed
        perbaruiDataSementara();
    }//GEN-LAST:event_btn_perbarisemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TambahData;
    private javax.swing.JPanel TampilanData;
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_batal1;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_hapusem;
    private javax.swing.JButton btn_perbarisem;
    private javax.swing.JButton btn_pilih;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_tambah1;
    private javax.swing.JButton btn_tambahsementara;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lb_satan;
    private javax.swing.JLabel lb_stok;
    private javax.swing.JLabel lb_total;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pn_detail;
    private javax.swing.JTable tbl_barang;
    private javax.swing.JTable tbl_detail;
    private javax.swing.JTable tbl_sementara;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JTextField txt_kodebarang;
    private javax.swing.JTextField txt_namabarang;
    private javax.swing.JTextField txt_no;
    private javax.swing.JTextField txt_satuan;
    private javax.swing.JTextField txt_stok;
    private javax.swing.JTextField txt_subtotal;
    private javax.swing.JTextField txt_tanggal;
    // End of variables declaration//GEN-END:variables

    private void dataTabel() {
        TambahData.setVisible(false);
        TambahData.setVisible(true);
        
        int row = tbl_barang.getSelectedRow();
        jLabel2.setText("Perbarui Data Jenis Barang");
        
//        txt_kodejenisbarang.setEnabled(false);
//        txt_namajenisbarang.setEnabled(true);
        
        
//        txt_kodejenisbarang.setText(tbl_barang.getModel().getValueAt(row, 1).toString());
//        txt_namajenisbarang.setText(tbl_barang.getModel().getValueAt(row, 2).toString());
     
        btn_tambah1.setText("PERBARUI");
        btn_batal.setVisible(true);
    }

    private void hapusData() {
        int index = tbl_barang.getSelectedRow();
        if(index !=-1){
            Model_Penjualan jbr = tblModel_penjualan.getData(tbl_barang.convertRowIndexToModel(index));
            if(JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus?", "Konfirmasi",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
                service_penjualan.hapusData(jbr);
                tblModel_penjualan.hapusData(index);
                loadData();
                resetForm();
                pn_detail.setVisible(false);
            }   
        }else{
            JOptionPane.showMessageDialog(null, "Pilih dulu record yang akan diupdate");
        }
    }

    private void tampilPanel() {
       mainPanel.removeAll();
       mainPanel.add(new Menu_Barangmasuk());
       mainPanel.repaint();
       mainPanel.revalidate();
    }

    private void loadData() {
        btn_hapus.setVisible(false);
        btn_batal.setVisible(false);
//        btn_print.setVisible(false);
        List<Model_Penjualan> list = service_penjualan.getData();
        tblModel_penjualan.setData(list);
//        setPreferredWidth();  // Memastikan bahwa metode setPreferredWidth dipanggil setelah memuat data
//        tbl_barang.revalidate();  // Menjalankan pembaruan UI
//        tbl_barang.repaint();  
    }

    private void simpanData() {
        String no = txt_no.getText();
        String tgl = txt_tanggal.getText();
        String kode = txt_kodebarang.getText();
        String nama = txt_namabarang.getText();
        Long total = Long.parseLong(lb_total.getText());
        
        Model_Barang brg = new Model_Barang();
        Model_Penjualan jual = new Model_Penjualan();
        Model_Detai_penjualan detJual = new Model_Detai_penjualan();
        
        //Ini untuk simpan penjualan bro
        jual.setId_penjualan(no);
        jual.setTanggal(tgl);
        jual.setTotal_harga(total);
        
        
        //SImpan tabel detail penjualan
        detJual.setMod_keluar(jual);
        detJual.setMod_barang(brg);
        
        service_penjualan.tambahData(jual);
        service_det.tambahData(detJual);
        service_det.hapusSementara(detJual);
        tblModel_penjualan.tambahData(jual);
        tampilPanel();
        loadData();
        resetForm();
        
   
    }

    private void perbaruiData() {
//        int index = tbl_barang.getSelectedRow();
//        if(index!=-1){
//            Model_Jenis_Barang mobar = tblModel.getData(tbl_barang.convertRowIndexToModel(index));
//            
//            if(servis.validasiNamaJenisBarang(mobar)==true)
//            {   
//                    if(validasiInput()== true){
//
////                        String kode_jenis = txt_kodejenisbarang.getText();
////                        String nama_jenis = txt_namajenisbarang.getText();
//
//                        Model_Jenis_Barang jbr = new Model_Jenis_Barang();
//
////                        jbr.setId_kategori(kode_jenis);               
////                        jbr.setNama_kategori(nama_jenis);
//
//                        servis.perbaruiData(jbr);
//                        tblModel.perbaruiData(index,jbr);
//
//                        loadData();
//                        resetForm();
//                        tampilPanel();          
//                } }else{
////            txt_namajenisbarang.requestFocus();
//        }    
//                
//            }
    }

    private void resetForm() {
        btn_tambah.requestFocus();
        btn_tambah.setText("TAMBAH");
//        txt_kodejenisbarang.setText("");
//        txt_namajenisbarang.setText("");
    }

    private boolean setPreferredWidth() {
        if (tbl_barang.getColumnCount() > 0) {
            tbl_barang.getColumnModel().getColumn(0).setPreferredWidth(20);
            tbl_barang.getColumnModel().getColumn(1).setPreferredWidth(269);
            tbl_barang.getColumnModel().getColumn(2).setPreferredWidth(269);
        }
         return false;
    }
  
    private void loadDataSementara() {
       List<Model_SemPenjualan> list = service_sem.getData();
       tblModel_sem.setData(list);
    }

    private void setTanggal() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void aktifBarang() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void bersihBarang() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void perbaruiDataSementara() {
        int index = tbl_sementara.getSelectedRow();
        if(index!=-1){
            Model_SemPenjualan model = tblModel_sem.getData(tbl_sementara.convertRowIndexToModel(index));
               
                String kode = txt_kodebarang.getText();
                String nama = txt_namabarang.getText();
                Long harga = Long.parseLong(txt_harga.getText());
                int jumlah = Integer.parseInt(txt_jumlah.getText());
                Long subtotal = Long.parseLong(txt_subtotal.getText());
                
                Model_Barang brg = new Model_Barang();
                Model_Detai_penjualan det_jual = new Model_Detai_penjualan();
                Model_SemPenjualan sem_jual = new Model_SemPenjualan();
                
                brg.setId_produk(kode);
                brg.setNama_produk(nama);
                brg.setHarga(harga);
                det_jual.setJumlah(jumlah);
                det_jual.setSub_total(subtotal);
                
                sem_jual.setMod_bararang(brg);
                sem_jual.setMod_detpenjualan(det_jual);
                

                service_sem.perbaruiData(sem_jual);
                tblModel_sem.perbaruiData(index, sem_jual);
                service_det.sumTotal(det_jual);
                lb_total.setText(det_jual.getSub_total().toString());
                loadDataSementara();
                bersihBarang();
                resetForm();
    }    
    
}
}
