/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import image.Menuitem;
import view.beranda;


/**
 *
 * @author UsEr
 */
public class Menu_Utama extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Utama
     */
    public Menu_Utama() {//String Id, String Nama
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_sidebar = new javax.swing.JPanel();
        pn_menu = new javax.swing.JPanel();
        pn_conten = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 51));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pn_sidebar.setBackground(new java.awt.Color(209, 213, 229));
        pn_sidebar.setForeground(new java.awt.Color(248, 249, 253));
        pn_sidebar.setPreferredSize(new java.awt.Dimension(200, 417));

        pn_menu.setBackground(new java.awt.Color(60, 211, 173));
        pn_menu.setLayout(new javax.swing.BoxLayout(pn_menu, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout pn_sidebarLayout = new javax.swing.GroupLayout(pn_sidebar);
        pn_sidebar.setLayout(pn_sidebarLayout);
        pn_sidebarLayout.setHorizontalGroup(
            pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_menu, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        pn_sidebarLayout.setVerticalGroup(
            pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );

        getContentPane().add(pn_sidebar, java.awt.BorderLayout.LINE_START);

        pn_conten.setBackground(new java.awt.Color(234, 238, 237));

        pn_utama.setBackground(new java.awt.Color(255, 255, 255));
        pn_utama.setName(""); // NOI18N
        pn_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pn_contenLayout = new javax.swing.GroupLayout(pn_conten);
        pn_conten.setLayout(pn_contenLayout);
        pn_contenLayout.setHorizontalGroup(
            pn_contenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_contenLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        pn_contenLayout.setVerticalGroup(
            pn_contenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_contenLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        getContentPane().add(pn_conten, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(6, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        setSize(new java.awt.Dimension(784, 494));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       pn_utama.add(new beranda());
       pn_utama.repaint();
       pn_utama.revalidate();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//               System.out.println("Menampilkan frame Menu_Utama");
            new Menu_Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pn_conten;
    private javax.swing.JPanel pn_menu;
    private javax.swing.JPanel pn_sidebar;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables

    private void execute() {
        //PUNYA MENU HOME
        ImageIcon iconhome = new ImageIcon(getClass().getResource("/image/home.png"));
        Menuitem menuhome = new Menuitem(iconhome, false, null, "Home", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
                pn_utama.add(new beranda());
                pn_utama.repaint();
                pn_utama.revalidate();
            }
        });
        
//        PUNYA MENU BARANG
        ImageIcon iconbarang = new ImageIcon(getClass().getResource("/image/barang.png"));
        ImageIcon icondata = new ImageIcon(getClass().getResource("/image/home.png"));
        ImageIcon iconkategori = new ImageIcon(getClass().getResource("/image/home.png"));
        
        
        
         Menuitem menukategori = new Menuitem(null, true, iconkategori, "Jenis Barang", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
                pn_utama.add(new Menu_Jenis());
                pn_utama.repaint();
                pn_utama.revalidate();
            }
        });
        
        Menuitem menudata = new Menuitem(null, true, icondata, "Data Barang", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
                pn_utama.add(new Menu_Barang());
                pn_utama.repaint();
                pn_utama.revalidate();

            }
        });
        
        Menuitem menupemasok = new Menuitem(null, true, icondata, "Pemasok", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
                pn_utama.add(new Menu_Pemasok());
                pn_utama.repaint();
                pn_utama.revalidate();

            }
        });
//       
//     
        Menuitem MenuBarang = new Menuitem(iconbarang, false, null, "Barang", null, menukategori,menudata, menupemasok);
        
//        //PUNYA MENU PEMESANAN
        ImageIcon iconkasir = new ImageIcon(getClass().getResource(""));
        Menuitem menuPemesanan = new Menuitem(iconkasir, false, null, "Pembelian", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
                pn_utama.add(new Menu_Penjualan());
                pn_utama.repaint();
                pn_utama.revalidate();
            }
        });
        
        Menuitem MenuTransaksi = new Menuitem(iconbarang, false, null, "Transaksi", null, menuPemesanan);

        
//        
//        //PUNYA LAPORAN
//        
        ImageIcon iconlaporan = new ImageIcon(getClass().getResource("/image/lapor.png"));
        
        Menuitem menustok = new Menuitem(null, true, icondata, "Stok", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
                pn_utama.add(new Menu_Laporan_Produk());
                pn_utama.repaint();
                pn_utama.revalidate();
                }
        });
        
        Menuitem menupembeli = new Menuitem(null, true, iconkategori, "Pembeli", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
//                pn_utama.add(new FromLaporanPembelian());
                pn_utama.repaint();
                pn_utama.revalidate();
                }
            
        });
        Menuitem menuLaporan = new Menuitem(iconlaporan, false, null, "Laporan", null, menustok, menupembeli);
       
//        
//        
        ImageIcon iconkeluar = new ImageIcon(getClass().getResource("/image/keluar.png"));
        Menuitem menukeluar = new Menuitem(iconkeluar, false, null, "Keluar", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
//                if(JOptionPane.showConfirmDialog(null, "Yakin Keluar?", "Keluar", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION){
//                    System.exit(0);
//                }
          
        login Mu = new login();
        Mu.show();
        
        dispose();
            }
        });
        
        
        
        
        //UNTUK MANGGIL MENU
        addMenu (menuhome,MenuBarang, MenuTransaksi, menuLaporan, menukeluar);
        
        
    }
    private void addMenu(Menuitem... menu){
        for (int i = 0; i < menu.length; i++){
            pn_menu.add(menu[i]);
            ArrayList<Menuitem> subMenu = menu[i].getSubMenu();
            for (Menuitem m :subMenu){
                addMenu (m);
            }
        }
        pn_menu.revalidate();
    }
}
