/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package custom;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author UsEr
 */
public class card_polos2 extends javax.swing.JPanel {

    private Color color1;
    private Color color2;

    public Color getColor1() {
        return color1;
    }

    public void setColor1(Color color1) {
        this.color1 = color1;
    }

    public Color getColor2() {
        return color2;
    }

    public void setColor2(Color color2) {
        this.color2 = color2;
    }
    
//    public card(Color color1, Color color2, JLabel lbTitle, JLabel lbIcon, JLabel lbValues, JLabel lbDescription){
//        this.color1 = color1;
//        this.color2 = color2;
//        this.lbIcon = lbIcon;
//        this.lbTitle = lbTitle;
//        this.lbValues = lbValues;
//        this.lbdescription = lbdescription;
//        
//    }
    
    public card_polos2() {
        initComponents();
        setOpaque(false);    
        color1 = Color.BLUE;
        color2 = Color.WHITE;
    }

    @Override
    protected void paintComponent(Graphics andre) {
        Graphics2D g2 = (Graphics2D) andre;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint dani = new GradientPaint(0, 0, color1, 0, getHeight(), color2);
        g2.setPaint(dani);
        g2.fillRoundRect(0, 0,  getWidth(), getHeight(), 40, 40);
        super.paintComponent(andre); 
        g2.setColor(new Color(255,255,255,50));
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

   
}
